trigger: 'none'

variables:
- name: tf_folder
  value: $(System.DefaultWorkingDirectory)/TerraformFiles

pool:
  vmImage: ubuntu-latest

steps:

- script: |
      docker run --tty --volume $(tf_folder):/tf bridgecrew/checkov --directory /tf --compact
  displayName: Run Static Code analysis for Terraform using Checkov