trigger: 'none'

pool:
          vmImage: 'windows-2019'

variables:
    environment1: Dev
    environment2: Prod
    region1: 'East US'
    region2: 'East US2'
    admin_username: 'azureadmin'

parameters:
  - name: runCompletePipeline
    displayName: Run All Tasks?
    default: true
    type: boolean


stages: 
  - stage: 'Build_Stage'
    displayName: 'Build Apps'
    jobs:
      - job: WebApp
        displayName: 'Build WebApp'
        variables:
          BuildConfiguration: Release

        steps:

        - task: DotNetCoreCLI@2
          displayName: "Dotnet Restore"
          inputs:
            command: restore
            projects: '**/WebApp.csproj'
        

        - task: DotNetCoreCLI@2
          displayName: "Dotnet Build"
          inputs:
            projects: '**/WebApp.csproj'
            arguments: '--configuration $(BuildConfiguration)'

        - task: DotNetCoreCLI@2
          displayName: Test
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            command: test
            projects: '**/WebApp*[Tt]est*.csproj'
            arguments: '--configuration $(BuildConfiguration)'

        - task: DotNetCoreCLI@2
          displayName: Publish
          inputs:
            command: publish
            publishWebProjects: True
            arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
            zipAfterPublish: True

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact'
          inputs:
            PathtoPublish: '$(build.artifactstagingdirectory)'
            ArtifactName: WebApp


      - job: Database
        displayName: 'Build DB Project to generate .dacpac file'
        dependsOn: WebApp
        condition: succeeded('WebApp')
        pool:
          vmImage: 'windows-2019'

        steps:

        - task: MSBuild@1
          displayName: 'Build solution WebApp.Database/WebApp.Database.sqlproj'
          inputs:
            solution: WebApp.Database/WebApp.Database.sqlproj
            msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'
            clean: true

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: DB .dacpac File'
          inputs:
            ArtifactName: DB


      - job: 'Selenium'
        displayName: 'Build UI Tests'
        dependsOn: Database
        condition: succeeded('Database')
        pool:
          vmImage: 'windows-2019'
        steps:
        
        - task: NuGetToolInstaller@1
          displayName: 'Use NuGet 6.6.1'
          inputs:
            versionSpec: 6.6.1
        
        - task: NuGetCommand@2
          displayName: 'NuGet restore'
          inputs:
              restoreSolution: WebAppWithDatabase.sln

        - task: MSBuild@1
          displayName: 'Build solution SeleniumUiTests/SeleniumUiTests.csproj'
          inputs:
            solution: SeleniumUiTests/SeleniumUiTests.csproj
            msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'

        - task: DeleteFiles@1
          displayName: 'Delete Old Chrome Driver'
          inputs:
            SourceFolder: '$(Build.ArtifactStagingDirectory)'
            Contents: '*chrome*driver*'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: UI'
          inputs:
            ArtifactName: UI


      - job: 'Terraform'
        displayName: 'Copy Terraform .tf files and publish them'
        dependsOn: Selenium
        condition: succeeded('Database')
        pool:
          vmImage: 'windows-2019'
        steps:
        
        - task: CopyFiles@2
          displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
          inputs:
            SourceFolder: TerraformFiles
            Contents: '*.tf'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: Terraform'
          inputs:
            ArtifactName: Terraform


  - template: azure-pipelines_CD_demo.yml
    parameters:
      environment: ${{variables.environment1}}
      region: ${{variables.region1}}
      admin_username: ${{variables.admin_username}}
      dependsOn: ['Build_Stage']


  - template: azure-pipelines_CD_demo.yml
    parameters:
      environment: ${{variables.environment2}}
      region: ${{variables.region2}}
      admin_username: ${{variables.admin_username}}
      dependsOn: ['Deployment']