parameters:
  environment: UAT
  region: "West US"
  admin_username: "azureadmin1"


stages:
  - stage: ${{parameters.environment}}
    variables: 
      env: ${{lower(parameters.environment)}}
    displayName: "Deployment to ${{parameters.environment}} Env"
    jobs:

      - job: "Deployment"
        pool: server

        steps:
          

          - task: ManualValidation@0
            condition: ${{ eq(lower(parameters.environment), 'prod') }}
            timeoutInMinutes: 60
            displayName: "Prod Deployment Validation"
            inputs:
              notifyUsers: 'aniket.p.deshmukh@gmail.com'
              instructions: 'Please validate the build $(Build.BuildId) configuration and resume'
              onTimeout: 'resume'

      - job: "Echo"
        dependsOn: Deployment
        pool:
           vmImage: ubuntu-20.04
        steps:
          - checkout: none
          - task: CmdLine@2
            continueOnError: true
            inputs:
              script: |
                echo $(webappurl)
                echo $(ConnectionString)
