
trigger: none

pool:
  vmImage: ubuntu-latest


steps:


- task: AzureKeyVault@2
  displayName: 'Azure Key Vault Secrete Retrieve'
  inputs:
    azureSubscription: 'Pay-As-You-Go (36e5119a-ef0e-4643-a46a-4a137216c264)'
    KeyVaultName: 'mydemo-ado-kv'
    SecretsFilter: '*'
    RunAsPreJob: false
  enabled: false

- script: |
   echo $(adminpassword)
   echo $(adminpassword) > $(Build.ArtifactStagingDirectory)/secrettest.txt


- script: |
   echo $(adminpassword)
   echo $(adminpassword) > $(Build.ArtifactStagingDirectory)/secrettest1.txt


- script: |
   echo $(adminpassword)
   echo $(adminpassword) > $(Build.ArtifactStagingDirectory)/secrettest2.txt

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'