trigger: 'none'

pool:
          vmImage: 'windows-2019'

variables:
    environment1: Test
    environment2: UAT
    region: 'East US'
    admin_username: 'azureadmin'
    group: KeyVaultSecret

parameters:
  - name: runCompletePipeline
    displayName: Run All Tasks?
    default: true
    type: boolean


stages: 
  - stage: 'Build_Stage'
    displayName: 'Build Apps'
    jobs:
      - job: WebApp
        displayName: 'Build WebApp'
        variables:
          BuildConfiguration: Release

        steps:

        - task: DotNetCoreCLI@2
          displayName: Restore
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            command: restore
            projects: '**/WebApp.csproj'
        
        - task: PowerShell@2
          displayName: 'PowerShell Script'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            targetType: filePath
            filePath: './sonar-add-project-guid.ps1'
            workingDirectory: WebApp

        - task: DotNetCoreCLI@2
          displayName: Build
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            projects: '**/WebApp.csproj'
            arguments: '--configuration $(BuildConfiguration)'

        - task: DotNetCoreCLI@2
          displayName: Test
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            command: test
            projects: '**/WebApp*[Tt]est*.csproj'
            arguments: '--configuration $(BuildConfiguration)'

        - task: DotNetCoreCLI@2
          displayName: Publish
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            command: publish
            publishWebProjects: True
            arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
            zipAfterPublish: True

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            PathtoPublish: '$(build.artifactstagingdirectory)'
            ArtifactName: WebApp

    
      - job: Database
        displayName: 'Build DB Project to generate .dacpac file'
        dependsOn: WebApp
        pool:
          vmImage: 'windows-2019'

        steps:

        - task: MSBuild@1
          displayName: 'Build solution WebApp.Database/WebApp.Database.sqlproj'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            solution: WebApp.Database/WebApp.Database.sqlproj
            msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'
            clean: true

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: DB .dacpac File'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            ArtifactName: DB
      
      - job: 'Selenium'
        displayName: 'Build UI Tests'
        dependsOn: Database
        pool:
          vmImage: 'windows-2019'
        steps:
        
        - task: NuGetToolInstaller@1
          displayName: 'Use NuGet 6.6.1'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            versionSpec: 6.6.1
        
        - task: NuGetCommand@2
          displayName: 'NuGet restore'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
              restoreSolution: WebAppWithDatabase.sln

        - task: MSBuild@1
          displayName: 'Build solution SeleniumUiTests/SeleniumUiTests.csproj'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            solution: SeleniumUiTests/SeleniumUiTests.csproj
            msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'

        - task: DeleteFiles@1
          displayName: 'Delete Old Chrome Driver'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            SourceFolder: '$(Build.ArtifactStagingDirectory)'
            Contents: '*chrome*driver*'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: UI'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            ArtifactName: UI
          

      - job: 'Terraform'
        displayName: 'Copy Terraform .tf files and publish them'
        dependsOn: Selenium
        pool:
          vmImage: 'windows-2019'
        steps:
        
        - task: CopyFiles@2
          displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            SourceFolder: TerraformFiles
            Contents: '*.tf'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: Terraform'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            ArtifactName: Terraform

  - template: azure-pipelines_CD_2023.yml
    parameters:
      environment: ${{variables.environment1}}
      region: ${{variables.region}}
      admin_username: ${{variables.admin_username}}
      dependsOn: ['Build_Stage']
  