trigger: 'none'

parameters:
  - name: runCompletePipeline
    displayName: Run All Tasks?
    default: true
    type: boolean


stages: 
  - stage: 'Build_Stage'
    displayName: 'Build Apps'
    jobs:
      - job: WebApp
        displayName: 'Build WebApp'
        pool:
          vmImage: 'windows-2019'
        variables:
          BuildConfiguration: Release

        steps:
        - checkout: none
        - task: DotNetCoreCLI@2
          displayName: Restore
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            command: restore
            projects: '**/WebApp.csproj'
        
        - task: PowerShell@2
          displayName: 'PowerShell Script'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            targetType: filePath
            filePath: './sonar-add-project-guid.ps1'
            workingDirectory: WebApp

        - task: DotNetCoreCLI@2
          displayName: Build
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            projects: '**/WebApp.csproj'
            arguments: '--configuration $(BuildConfiguration)'

        - task: DotNetCoreCLI@2
          displayName: Test
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            command: test
            projects: '**/WebApp*[Tt]est*.csproj'
            arguments: '--configuration $(BuildConfiguration)'

        - task: DotNetCoreCLI@2
          displayName: Publish
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            command: publish
            publishWebProjects: True
            arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
            zipAfterPublish: True

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            PathtoPublish: '$(build.artifactstagingdirectory)'
            ArtifactName: WebApp

    
      - job: Database
        displayName: 'Build DB Project to generate .dacpac file'
        dependsOn: WebApp
        pool:
          vmImage: 'windows-2019'

        steps:
        - checkout: none
        - task: MSBuild@1
          displayName: 'Build solution WebApp.Database/WebApp.Database.sqlproj'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            solution: WebApp.Database/WebApp.Database.sqlproj
            msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'
            clean: true

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: DB .dacpac File'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            ArtifactName: DB
      
      - job: 'Selenium'
        displayName: 'Build UI Tests'
        dependsOn: Database
        pool:
          vmImage: 'windows-2019'
        steps:
        - checkout: none
        - task: NuGetToolInstaller@1
          displayName: 'Use NuGet 6.6.1'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            versionSpec: 6.6.1
        
        - task: NuGetCommand@2
          displayName: 'NuGet restore'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
              restoreSolution: WebAppWithDatabase.sln

        - task: MSBuild@1
          displayName: 'Build solution SeleniumUiTests/SeleniumUiTests.csproj'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            solution: SeleniumUiTests/SeleniumUiTests.csproj
            msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'

        - task: DeleteFiles@1
          displayName: 'Delete Old Chrome Driver'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            SourceFolder: '$(Build.ArtifactStagingDirectory)'
            Contents: '*chrome*driver*'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: UI'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            ArtifactName: UI
          

      - job: 'Terraform'
        displayName: 'Copy Terraform .tf files and publish them'
        dependsOn: Selenium
        pool:
          vmImage: 'windows-2019'
        steps:
        - checkout: none
        - task: CopyFiles@2
          displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            SourceFolder: TerraformFiles
            Contents: '*.tf'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: Terraform'
          enabled: ${{parameters.runCompletePipeline}}
          inputs:
            ArtifactName: Terraform


  - stage: 'Test_Env_Stage'
    dependsOn:
    - 'Build_Stage'
    displayName: 'Deployment to Test Env'
    jobs:
      - job: 'Terraform'
        displayName: 'Infra Deployment with TF'
        pool:
          vmImage: 'windows-2019'

        steps:
        - checkout: none

        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'specific'
            project: 'c3e77991-53e0-4a51-a181-ce6611863016'
            pipeline: '13'
            buildVersionToDownload: 'specific'
            buildId: '62'
            downloadType: 'single'
            artifactName: 'Terraform'
            downloadPath: '$(System.DefaultWorkingDirectory)'


        - task: TerraformInstaller@1
          displayName: 'Terraform Installation'
          inputs:
            terraformVersion: 'latest'
          
        - task: TerraformTaskV4@4
          displayName: 'Terraform Init'
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
            backendServiceArm: 'Pay-As-You-Go (36e5119a-ef0e-4643-a46a-4a137216c264)'
            backendAzureRmResourceGroupName: 'DevOpsDemoADO'
            backendAzureRmStorageAccountName: 'myadodemostorageaccount'
            backendAzureRmContainerName: 'statefile'
            backendAzureRmKey: 'terraform.tfstate'
          
          
        - task: TerraformTaskV4@4
          displayName: 'Terraform Validate'
          inputs:
            command: validate
            workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'

        - task: TerraformTaskV4@4
          displayName: 'Terraform Plan'
          inputs:
            command: plan
            workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
            commandOptions: '-var admin_password=$(admin_password)'
            environmentServiceNameAzureRM: 'Pay-As-You-Go (36e5119a-ef0e-4643-a46a-4a137216c264)'
            backendServiceArm: 'Pay-As-You-Go (36e5119a-ef0e-4643-a46a-4a137216c264)'
            backendAzureRmResourceGroupName: DevOpsDemoADO
            backendAzureRmStorageAccountName: myadodemostorageaccount
            backendAzureRmContainerName: statefile
            backendAzureRmKey: terraform.tfstate


        - task: TerraformTaskV4@4
          displayName: 'Terraform Apply'
          inputs:
            command: apply
            workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
            commandOptions: '-var admin_password=$(admin_password)'
            environmentServiceNameAzureRM: 'Pay-As-You-Go (36e5119a-ef0e-4643-a46a-4a137216c264)'


      - job: 'App_Service_Deployment'
        dependsOn: Modify_Appsettings_File
        displayName: 'Azure App Service Deploy: my-service-my-ado-demo-test'
        pool:
          vmImage: 'windows-2019'

        steps:
        - checkout: none

        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'specific'
            project: 'c3e77991-53e0-4a51-a181-ce6611863016'
            pipeline: '13'
            buildVersionToDownload: 'specific'
            buildId: '62'
            downloadType: 'single'
            artifactName: 'WebApp'
            downloadPath: '$(System.DefaultWorkingDirectory)'

        - task: FileTransform@1
          displayName: 'Modify Appsettings: SQL DB Connection String'
          inputs:
            folderPath: '$(System.DefaultWorkingDirectory)/WebApp/WebApp.zip'
            fileType: json
            targetFiles: appsettings.json

        - task: AzureRmWebAppDeployment@4
          displayName: 'Azure App Service Deploy: my-service-my-ado-demo-test'
          inputs:
            azureSubscription: 'Pay-As-You-Go (36e5119a-ef0e-4643-a46a-4a137216c264)'
            appType: webAppLinux
            WebAppName: 'my-service-my-ado-demo-test'
            packageForLinux: '$(System.DefaultWorkingDirectory)/WebApp/WebApp.zip'
            JSONFiles: '**/appsettings.json'

      - job: 'DB_Publish'
        dependsOn: App_Service_Deployment
        displayName: 'Azure SQL DacpacTask'
        pool:
          vmImage: 'windows-2019'

        steps:
        - checkout: none

        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'specific'
            project: 'c3e77991-53e0-4a51-a181-ce6611863016'
            pipeline: '13'
            buildVersionToDownload: 'specific'
            buildId: '62'
            downloadType: 'single'
            artifactName: 'DB'
            downloadPath: '$(System.DefaultWorkingDirectory)'

        - task: SqlAzureDacpacDeployment@1
          displayName: 'Azure SQL DacpacTask'
          inputs:
            azureSubscription: 'Pay-As-You-Go (36e5119a-ef0e-4643-a46a-4a137216c264)'
            AuthenticationType: connectionString
            ConnectionString: 'Server=tcp:my-service-my-ado-demo-db-server-test.database.windows.net,1433;Initial Catalog=my-service-my-ado-demo-db-test;Persist Security Info=False;User ID=azureadmin;Password=$(admin_password);MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
            DacpacFile: '$(System.DefaultWorkingDirectory)/DB/WebApp.Database.dacpac'

      - job: 'Selenium'
        displayName: 'Run UI Tests'
        dependsOn: DB_Publish
        pool:
          vmImage: 'windows-2019'
        steps:
        - checkout: none

        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'specific'
            project: 'c3e77991-53e0-4a51-a181-ce6611863016'
            pipeline: '13'
            buildVersionToDownload: 'specific'
            buildId: '62'
            downloadType: 'single'
            artifactName: 'UI'
            downloadPath: '$(System.DefaultWorkingDirectory)'
        - task: VSTest@2
          inputs:
            testSelector: 'testAssemblies'
            testAssemblyVer2: |
              $(System.DefaultWorkingDirectory)/UI/*Test*.dll
              !**\*TestAdapter.dll
              !**\obj\**
            searchFolder: '$(System.DefaultWorkingDirectory)'
            runSettingsFile: '$(System.DefaultWorkingDirectory)/UI/.runsettings'
            overrideTestrunParameters: '-webAppUrl $(webappurl)'
            codeCoverageEnabled: true
      
      - job: 'Sleep'
        pool:
          vmImage: 'windows-2019'
        displayName: 'Sleep for 2mins'
        dependsOn: Selenium
        steps:
        - powershell: |
            # Write your PowerShell commands here.
            
            Start-Sleep -Seconds 120