trigger: 'none'


jobs:
- job: WebApp
  displayName: 'Build WebApp'
  pool:
    vmImage: 'windows-2019'
  variables:
    BuildConfiguration: Release

  steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/WebApp.csproj'
    
    - task: PowerShell@2
      displayName: 'PowerShell Script'
      inputs:
        targetType: filePath
        filePath: './sonar-add-project-guid.ps1'
        workingDirectory: WebApp

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: '**/WebApp.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/WebApp*[Tt]est*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: WebApp
      condition: succeeded()

- job: Database
  displayName: 'Build DB Project to generate .dacpac file'
  dependsOn: WebApp
  pool:
    vmImage: 'windows-2019'

  steps:

    - task: MSBuild@1
      displayName: 'Build solution WebApp.Database/WebApp.Database.sqlproj'
      inputs:
        solution: WebApp.Database/WebApp.Database.sqlproj
        msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'
        clean: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: DB .dacpac File'
      inputs:
        ArtifactName: DB
  
- job: 'Selenium'
  displayName: 'Build UI Tests'
  dependsOn: Database
  pool:
    vmImage: 'windows-2019'
  steps:
    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet 6.6.1'
      inputs:
        versionSpec: 6.6.1

    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        restoreSolution: WebAppWithDatabase.sln

    - task: MSBuild@1
      displayName: 'Build solution SeleniumUiTests/SeleniumUiTests.csproj'
      inputs:
        solution: SeleniumUiTests/SeleniumUiTests.csproj
        msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'

    - task: DeleteFiles@1
      displayName: 'Delete Old Chrome Driver '
      inputs:
        SourceFolder: '$(Build.ArtifactStagingDirectory)'
        Contents: '*chrome*driver*'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: UI'
      inputs:
        ArtifactName: UI

- job: 'Terraform'
  displayName: 'Copy Terraform .tf files and publish them'
  dependsOn: Selenium
  pool:
    vmImage: 'windows-2019'
  steps:
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: TerraformFiles
        Contents: '*.tf'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: Terraform'
      inputs:
        ArtifactName: Terraform